# Hypermedia Actions Configuration
# This file defines the hypermedia affordances for each model and their actions
# Supports dynamic ID replacement with #ID placeholder

Article:
  # Collection actions
  index:
    rel: 'collection'
    method: 'GET'
    link: '/articles'
  
  new:
    rel: 'new'
    method: 'GET'
    link: '/articles/new'
  
  create:
    rel: 'create'
    method: 'POST'
    link: '/articles'
  
  # Resource actions
  show:
    rel: 'self'
    method: 'GET'
    link: '/articles/#ID'
  
  destroy:
    rel: 'delete'
    method: 'DELETE'
    link: '/articles/#ID'
    confirm: 'Are you sure?'
  
  # FSM State Transitions
  submit:
    rel: 'transition:submit'
    method: 'POST'
    link: '/articles/#ID/submit'
  
  reject:
    rel: 'transition:reject'
    method: 'POST'
    link: '/articles/#ID/reject'
  
  approve_private:
    rel: 'transition:approve_private'
    method: 'POST'
    link: '/articles/#ID/approve_private'
  
  resubmit:
    rel: 'transition:resubmit'
    method: 'POST'
    link: '/articles/#ID/resubmit'
  
  archive:
    rel: 'transition:archive'
    method: 'POST'
    link: '/articles/#ID/archive'
  
  publish:
    rel: 'transition:publish'
    method: 'POST'
    link: '/articles/#ID/publish'
  
  make_visible:
    rel: 'transition:make_visible'
    method: 'POST'
    link: '/articles/#ID/make_visible'
  
  make_invisible:
    rel: 'transition:make_invisible'
    method: 'POST'
    link: '/articles/#ID/make_invisible'

Comment:
  # Collection actions
  index:
    rel: 'collection'
    method: 'GET'
    link: '/articles/#ARTICLE_ID/comments'
  
  new:
    rel: 'new'
    method: 'GET'
    link: '/articles/#ARTICLE_ID/comments/new'
  
  create:
    rel: 'create'
    method: 'POST'
    link: '/articles/#ARTICLE_ID/comments'
  
  # Resource actions
  show:
    rel: 'self'
    method: 'GET'
    link: '/comments/#ID'
  
  edit:
    rel: 'edit'
    method: 'GET'
    link: '/comments/#ID/edit'
  
  destroy:
    rel: 'delete'
    method: 'DELETE'
    link: '/comments/#ID'
    confirm: 'Are you sure you want to delete this comment?'
  
  # FSM State Transitions
  approve:
    rel: 'transition:approve'
    method: 'POST'
    link: '/comments/#ID/approve'
  
  reject:
    rel: 'transition:reject'
    method: 'POST'
    link: '/comments/#ID/reject'
  
  delete:
    rel: 'transition:delete'
    method: 'POST'
    link: '/comments/#ID/delete'
    confirm: 'Delete this comment?'
  
  restore:
    rel: 'transition:restore'
    method: 'POST'
    link: '/comments/#ID/restore'
# Navigation links
Navigation:
  all_articles:
    rel: 'collection'
    method: 'GET'
    link: '/articles'
  
  my_articles:
    rel: 'my-articles'
    method: 'GET'
    link: '/articles/my_articles'
  
  review_articles:
    rel: 'review-articles'
    method: 'GET'
    link: '/articles/articles_for_review'
    admin_only: true
  
  deleted_articles:
    rel: 'deleted-articles'
    method: 'GET'
    link: '/articles/deleted_articles'
    admin_only: true

  pending_comments:
    rel: 'pending-comments'
    method: 'GET'
    link: '/comments/pending_comments'
    admin_only: true

  state_transitions:
    rel: 'state-transitions'
    method: 'GET'
    link: '/state_transitions'
    admin_only: true
  
  sign_in:
    rel: 'sign-in'
    method: 'GET'
    link: '/users/sign_in'
  
  sign_up:
    rel: 'sign-up'
    method: 'GET'
    link: '/users/sign_up'
  
  sign_out:
    rel: 'sign-out'
    method: 'DELETE'
    link: '/users/sign_out'
  
  custom_template:
    rel: 'custom-template'
    method: 'GET'
    link: '/custom_template'
